### ISSUE TITLE
Move from Travis CI to GitHub Actions?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [sile/hash_ring#5]
Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions, or at least adds GitHub Actions alongside Travis CI? It seems travis-ci.org will stop being useful from Dec 31 2020. I can do it, except that I think you need to create the workflow yml, first, in `master`, after which I can branch off of.

**Comment by sile** [comment]
> Would you be interested in a pull request that moves CI from Travis CI to GitHub Actions

Definitely, yes!
I'd really appreciate it if you could do that.

> you need to create the workflow yml, first, in `master`

I can create the fie, but what the content should be? (is an empty yml file okay?)

**Comment by paulo-ferraz-oliveira** [comment]
You can create an empty file. I'm not sure if it'll work, though.

Try this, for example:
```
---
name: example
on:
  pull_request:
    branches:
      - master
jobs:
  example:
    name: Example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp_vsn: 23.1
    steps:
      - uses: actions/checkout@v2
      - run: rebar3 --version
```
